Unifying how panel column datatypes are ahndeled.
BodenmillerGroup/steinbock pull request #175
Opened 2023-02-24 14:05 UTC by Milad4849

Changed the pandas series dtype assignment of columns in `imc._clean_panel` to float.

2023-04-24 19:48 UTC, jwindhager commented
Hi Milad! Do you still need a review here? Also, this PR now seems to be for cellpose?

2023-04-25 08:03 UTC, Milad4849 commented
Hi Jonas, yes it would be great if you could review the cellpose2.0 part. The initial PR was a very minor issue, I added the cellpose commit on top. Would you normally do a separate PR?

2023-04-25 10:07 UTC, jwindhager commented
Ok, will review asap!

Regarding the PR: Yes, on the steinbock repository I'd usually develop in feature branches and merge them into the develop branch using separate PRs (gitflow without release branches, see [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)). This makes it easier to track changes and do reviews and such. But for now, lets just rename this PR :-)

2023-05-01 13:57 UTC, jwindhager requested changes
Hey @Milad4849, here are my 2C. As the primary maintainer of steinbock, please feel free to consider/ignore them as you wish.

2023-05-01 13:57 UTC, jwindhager commented on steinbock/segmentation/_cli/cellpose.py
> +            logger.info(mask_file)
A few comments:
- the second `if` should be an `elif`
- when using if/elif, please add an `else` branch, unless you can assert the values in `model_name`
- why is the if/else necessary here at all? According to the function's signature, `try_segment_objects` always returns a `diam`

2023-05-01 13:57 UTC, jwindhager commented on steinbock/segmentation/cellpose.py
> +        model = cellpose.models.CellposeModel(model_type=model_name, net_avg=net_avg)
Here:
- if/elif/else structure, see comment above (always cover all cases!)
- instead of if/elif/else, one could consider using `model_name -> model_type` mappings (e.g. `dict`) here, which are a bit easier to debug and maintain
- what's the benefit of using `Cellpose` (extends `CellposeModel`) for some values of `model_name` over using `CellposeModel` directly?

2023-05-01 13:57 UTC, jwindhager commented on steinbock/segmentation/cellpose.py
> +
Here:
- please avoid evaluating the same condition in multiple places (cf. the checks in line 82ff) to keep things maintainable (imagine another developer extending this in the future, not knowing where this condition is evaluated)
- also, is there maybe a default case? Imagine `cellpose` will be extended in the future - will the `steinbock` developers always need to explicitly add the new model names, or should e.g. `Cellpose` only be used for specific values of `model_name`, whereas `CellposeModel` should be by default for all others?
- as before, if/elif/else: what happens in case the `model_name` is not in the list of allowed values? --> currently, the return value would be `None`, which does not adhere to the function's signature. This is problematic, because developers currently can specify arbitrary values for `model_name` as per the function's signature. Better to add informative exception handling when expecting specific literals (in the previous version, checking `model_name` values was delegated to `Cellpose`).
- additionally, in the current version, not all return statements are compatible with the function's return type `Generator[Tuple[Path, np.ndarray, np.ndarray, np.ndarray, float], None, None]` (specifically, this is the case for the second if-block)
- in general, please do not use "dynamic" function signatures, whose return type depends on argument values! This necessitates unnecessary downstream conditionals (cf. the if/elif/else blocks in the CLI code above). Instead, use a single return type (preferred) or provide two different functions (not preferred due to code complexity/code duplication).

2023-05-02 12:39 UTC, Milad4849 commented on steinbock/segmentation/cellpose.py
> +
I revised the conditional statements as you suggest and avoided the dynamic function call. Now the ```CellposeModel ``` is the default call. At the end changes are only necessary in ```try_segment_objects```: a conditional statement to determine the cellpose model, a conditional statement to determine the output expected from ```model.eval``` , both based on the cellpose model choice, depending on the cellpose model and finally to and to pass a diameter =none, in case of an unsized model.

2023-05-02 12:39 UTC, Milad4849 commented on steinbock/segmentation/cellpose.py
> +        model = cellpose.models.CellposeModel(model_type=model_name, net_avg=net_avg)
Now, all conditional statements are here. The output of ```try_segment_objects``` is no longer dynamic, in case of an unsized models, a ```diameter=None``` is returned. Not sure mapping is more concise here as we are performing the comparison only once.

There are sized and unsized models in cellpose which require reperate calls; ```Cellpose ``` and ```CellposeModel ``` respectively.

2023-05-02 12:39 UTC, Milad4849 commented on steinbock/segmentation/_cli/cellpose.py
> +            logger.info(mask_file)
if/else removed from here, now it is back to original.

2023-05-02 13:34 UTC, jwindhager requested changes

2023-05-02 13:34 UTC, jwindhager commented on steinbock/preprocessing/imc.py
> +        panel["cellpose"] = pd.Series(dtype=float)
Looks like my previous comment got lost somehow.

Anyway, do we really want the ilastik/deepcell/cellpose columns to be non-nullable **floating point** numbers? Seems a bit counter-intuitive to me, especially considering that e.g. the channel/name/keep columns remain nullable. Also, if this change is merged, one should probably also adapt e.g. line 104 and others accordingly.

2023-05-02 13:34 UTC, jwindhager commented on steinbock/segmentation/cellpose.py
> +            output = model.eval(
Note that this overrides the previous initialization of `output`.

Also, it may be more readable to write something like:
```python
eval_results = model.eval(...)
masks, flows, styles = eval_results[:3]
if len(eval_results) > 3:
    diams = eval_results[3]
    diam = diams if isinstance(diams, float) else diams[0]
else:
    diam = None
yield Path(img_file), masks[0], flows[0], styles[0], diam
del img, masks, flows, styles
```

2023-05-02 13:34 UTC, jwindhager commented on steinbock/segmentation/cellpose.py
>  ) -> Generator[Tuple[Path, np.ndarray, np.ndarray, np.ndarray, float], None, None]:
```suggestion
) -> Generator[Tuple[Path, np.ndarray, np.ndarray, np.ndarray, Optional[float]], None, None]:
```

2023-08-23 11:15 UTC, merged