Enhanced error handling of corrupted IMC files with no recovery txt
BodenmillerGroup/steinbock pull request #190
Opened 2023-05-19 15:24 UTC by Milad4849

AS discussed in #184, now when an mcd file is corrupted and a recovery txt file is not found, an additional warning message is logged: "No corresponding recovery text file was found". I tested it using the corrupted mcd file provided by @nathansteenbuck.

2023-05-25 08:02 UTC, jwindhager requested changes

2023-05-25 08:02 UTC, jwindhager commented on steinbock/preprocessing/imc.py
> +                            logger.warning(f"No recovery text file was found")
I would include the MCD file & acquisition ID here

Btw, if you decide to not include that, this wouldn't need to be an f-string

2023-06-01 09:12 UTC, Milad4849 commented on steinbock/preprocessing/imc.py
> +                            logger.warning(f"No recovery text file was found")
Now the acquisition ID and file name are included with the logged message.

2023-06-01 09:12 UTC, Milad4849 commented on steinbock/preprocessing/imc.py
> +                            continue
It is not :) removed.

2023-06-01 09:15 UTC, jwindhager approved these changes

2023-06-01 09:16 UTC, jwindhager commented
Ah wait - why is this merged directly into main?

2023-08-10 15:04 UTC, merged